jobs:
  - job: Windows
    pool:
      vmImage: windows-2019
    strategy:
      matrix:
        node_10.x:
          node_version: 10.x
        node_12.x:
          node_version: 12.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js
      - script: yarn
        displayName: Install dependencies
      - script: yarn test --coverage
        displayName: Run tests

  - job: macOS
    pool:
      vmImage: macOS-10.15
    strategy:
      matrix:
        node_10.x:
          node_version: 10.x
        node_12.x:
          node_version: 12.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js
      - script: yarn
        displayName: Install dependencies
      - script: yarn test --coverage
        displayName: Run tests

  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node_10.x:
          node_version: 10.x
        node_12.x:
          node_version: 12.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js
      - script: yarn
        displayName: Install dependencies
      - script: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x8' yarn test --coverage
        displayName: Run tests
